---
title: "Servicio de bicis en NYC"
output: html_notebook
---

Veamos las ubicaciones de las estaciones en un mapa de la ciudad.

```{r}
library(leaflet)
library(magrittr)
stations <- readr::read_csv("dat/stations.csv")

colnames(stations)
colnames(stations) <- c("X1","station.id","station.name","latitude","longitude")
names(providers)
leaflet(options = leafletOptions(minZoom = 0, maxZoom = 18))
m <- leaflet(stations) %>% addTiles() %>% addProviderTiles(providers$MtbMap) %>%
  addProviderTiles(providers$Stamen.TonerLines,
    options = providerTileOptions(opacity = 0.35)) %>%
  addProviderTiles(providers$Stamen.TonerLabels) 
m %>% addCircles(color = "red",radius=5, opacity = T ) %>% addMarkers(popup = ~htmltools::htmlEscape(station.name)) 

```

Usuarios por edades y género.

```{r}
rutas <- readr::read_csv("dat/bike_nyc_1_6_2019.csv")
colnames(rutas)

usuarios <- rutas %>% dplyr::select(birth.year,gender) %>% 
  dplyr::mutate(age = lubridate::year(Sys.Date())-birth.year) %>% 
  dplyr::group_by(age,gender) %>% 
  dplyr::mutate(contador = n()) %>% 
  dplyr::group_by(age,gender,contador) %>% 
  dplyr::summarise()
  


```

